name: Push

on:
  push:
    tags:
      - v**

jobs:
  build:
    timeout-minutes: 30
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # <Special tagging for flux manifests
      - name: Prepare tag name from Release Tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      # Special tagging for flux manifests>

      - name: Set tag and image outputs (backend)
        id: set_tag
        run: |
          test -n "${TAG}" || TAG=temp-${GITHUB_SHA::8}-$(date +%s)
          IMAGE="ghcr.io/asilbek99/action-cleanup"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}
      # Setting default tag if none of above was set & Setting full image name>
      - name: Set up Docker buildX
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # WRKDR is a Github Actions workaround for WORKDIR in Dockerfiles. See Dockerfile

      - name: Build image
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          pull: true
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.set_tag.outputs.tagged_image }}


      - name: Scan image
        id: scan_backend
        uses: anchore/scan-action@v2
        with:
          image: ${{ steps.set_tag.outputs.tagged_image }}
          grype-version: 0.15.0
          severity-cutoff: critical
          fail-build: false
          acs-report-enable: true
      - name: Push image
        run: docker push ${{ steps.set_tag.outputs.tagged_image }}
